### ISSUE TITLE
Use proper package names

### ISSUE THREAD

**Issue by jomo** [RedstonerServer/redstoner-jutils#3]
from the java [docs](http://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html#jls-6.1):
> You form a unique package name by first having (or belonging to an organization that has) an Internet domain name, such as oracle.com. You then reverse this name, component by component, to obtain, in this example, com.oracle, and use this as a prefix for your package names, using a convention developed within your organization to further administer package names.

So this should be `com.redstoner.` for us.

**Comment by jomo** [comment]
@BitByteMC worked on this already, although only in 1 folder so far.

**Comment by BitByteMC** [comment]
I will see what I can do about fixing up the other packages quickly. Give me a minute.

**Comment by BitByteMC** [comment]
Issue fixed. [Referenced Commit.](https://github.com/RedstonerServer/redstoner-jutils/commit/938c510af7dfb7e87a476c7b5723fbabfde74058)

**Comment by jomo** [comment]
great, thanks
